# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
     # passos para criação de imagem no Docker
     # criação da imagem no docker
       # docker login
       # docker build
       # docker push
        
      - name: Autenticando usuário no repositorio de imagens do Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Construindo a nova imagem da aplicação e enviando ao Docker Hub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            ivanjuniordocker/kube-news:latest
            ivanjuniordocker/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      
      # definindo contexto do Kubernetes
      - name: (Action Kubernetes Set Context) - Defininco o kubeconfig
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig # especificação do kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}} # especifica o arquivo kube_config
         
      # para aplicar o deploy
      - name: (Action Deploy to Kubernetes cluster) - Efetuando o deploy no Kubernetes
        uses: Azure/k8s-deploy@v4.3
        with:
          images: ivanjuniordocker/kube-news:${{github.run_number}} # vao ser as imagens que vai alterar no manifesto
          manifests: k8s/deployment.yaml
